### ISSUE TITLE
Update the `how to get data` modal

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#367]
Once https://github.com/neurobagel/dataget/issues/9 is addressed:
- [x] Update the instructions for how to get data
- [x] Release query tool
- [x] ~Mention that users have to manually "CTRL+C" to exit otherwise the container will hang~ (edit: no longer needed now that we have an echo statement to signal script completion)

**Comment by alyssadai** [comment]
Hey @rmanaem, upon further reflection I realized that my suggestion to rename "How to get data" to "How to get data from datalad" might not be a good idea, since I forgot BIC users still need to view the modal for how to download the machine-readable TSV to feed to the dedicated BIC symlink script.

How about instead, having two sections in the modal, one of which is more generic:

```
Query results for programmatic use/download
  <any general info on the `cohort-participant-machine-results.tsv`>
```

```
Downloading matching subjects from DataLad datasets
  <info about using dataget>
```
(or something similar for section names)

For the BIC then, we could refer them to just the first section assuming they want to download the PD data. Meanwhile, for any users who want to download query results from DataLad datasets/OpenNeuro, both sections would be relevant.
